FROM node:20-alpine AS prune
WORKDIR /prune
COPY . .
RUN npm install -g turbo && turbo prune server --docker

FROM node:20-alpine AS dependencies
WORKDIR /dependencies
COPY --from=prune /prune/out/json/ .
COPY --from=prune /prune/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=prune /prune/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN npm install -g pnpm && pnpm install --frozen-lockfile --prod 