FROM nginx:alpine AS production
COPY ./apps/client/dist /usr/share/nginx/html
COPY ./apps/nginx/nginx.conf /etc/nginx/conf.d/default.conf
ENV PORT=5000
EXPOSE $PORT
ENV VITE_API_URL=''
CMD ["nginx", "-g", "daemon off;"]
