services:
    front-hub:
        image: cloud-canvas.kr.ncr.ntruss.com/front-hub:dev
        container_name: front-hub
        environment:
            BACK_URL: ${BACK_URL}
        ports:
            - '3000:3000'
        networks:
            - cloud-canvas-network
        restart: unless-stopped
        pull_policy: always
networks:
    cloud-canvas-network:
        driver: bridge
