FROM node:20-alpine AS production
WORKDIR /app
COPY ./apps/hub/.next/standalone/ ./standalone/
COPY ./apps/hub/.next/static/ ./standalone/apps/hub/.next/static/
COPY ./apps/hub/public/ ./standalone/apps/hub/public/

ENV BACK_URL=http://localhost:3000
ENTRYPOINT ["sh", "-c", "node ./standalone/apps/hub/server.js"]
